### ISSUE TITLE
Dashboard Sections should be collapsible

### ISSUE THREAD

**Issue by danielo515** [roma0104/gsd5#22]
Since the ability to select which list are part of the dashboard, sometimes you want to no see them all at a time. Adding the ability to collapse those sections will improve the user experience.

**Comment by roma0104** [comment]
Added tiddler toolbar button to minimize the BlueBox when desired.
dcc8c8a285c427bbd5c3e0d7dc8832a0f08a9e36

**Comment by roma0104** [comment]
Realized that I provided collapsing of the BlueBox and not lists.

**Comment by roma0104** [comment]
Added back to milestone, not sure why I removed that and marked resolved.
