### ISSUE TITLE
Give proper classes to buttons

### ISSUE THREAD

**Issue by danielo515** [roma0104/gsd5#32]
So I can style them without editing the core.
Currently many buttons suitable of customization just have generic classes like tc-btn-invisible. The plus sign is a good example. I want to make that button bigger on mobile with CSS media queries, but I can not because it does not have any class that I can refer.

**Comment by roma0104** [comment]
Added classes to the "+" for new actions in the Project lists and made the plus glyph larger by default.  I find the larger glyph personally not too difficult to touch on a iPhone 4S, but that is the only touch, mobile device I have easy access to.  

Other widgets found in the bluebox now have classes for future CSS improvements but currently just have references and no customised CSS.

**Comment by danielo515** [comment]
Hello,

I think it will be more useful if you give the class to the button instead of the span inside the button. That way people can style the button itself, and if they want they can style its children. This way you open a door for theme creation.

**Comment by roma0104** [comment]
Hey Danielo,

I found your issue with how it was done.  It had a vestigial macro from when I was first hacking this thing together; I removed the class macro and added the more appropriate classes.  You should see the commit in a few hours.

For the other widgets with classes on paragraph or span tags:
I classed the paragraph for a particular reason, whether it is correct to do so, I don't know.  I added the class to the span so a person can style the text that may not structurally be inside the widget.  Then the author can use CSS selectors like: `.gsd-bluebox-droplist button { ... }` to actually style the button itself.

**Comment by danielo515** [comment]
Hello @roma0104 

Currently it is like this 

```
 <$button> <span> text</span></$button>
```

So if the class is on the span, there is no way to access the button with the notation you have posted

.class button {
}

If the class is on the button, instead, you can use the method you described.

**Comment by roma0104** [comment]
I think this corrected the concern you were having with button classes.
fd74e4642b8588bc8d0d6f9872766f47f687f886
If this did not please tell me which part of the code specifically.  Additionally, if you find some more buttons that need some classes please tell me.  I did a quick search for buttons needing classes.

**Comment by danielo515** [comment]
Yes, commit fd74e46 is exactly what I was asking for. If I find more buttons or UI elements that claims for a class I will let you know with a new issue.

Thanks!
