### ISSUE TITLE
Done Actions Shown in Action-Depend Droplist

### ISSUE THREAD

**Issue by roma0104** [roma0104/gsd5#35]
Done actions are shown in droplist for dependant actions.
Filter adjustment.

**Comment by danielo515** [comment]
This is really annoying

**Comment by roma0104** [comment]
Yeah I agree.  With US holidays over, I will get some work done on these
little dangling bugs.

On Tue, Jan 6, 2015 at 3:52 PM, danielo515 <notifications@github.com> wrote:

> This is really annoying
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roma0104/gsd5/issues/35#issuecomment-68940649>.
>



-- 
Roma Quintin Hicks

**Comment by roma0104** [comment]
0d129cb0ee7e181fc674a32e32f9a838e4dd84b6
