### ISSUE TITLE
Create User Preference for Open Action/Project on Creation

### ISSUE THREAD

**Issue by roma0104** [roma0104/gsd5#37]
Give users the option to open action and project tiddlers after creation.  Otherwise, new action/projects will just appear in the list to be open at a later point for editing.

Expand the functionality of #23.

**Comment by danielo515** [comment]
Very useful for fast note taking. One thing you may also consider is, when creating a task from the sidebar provide a drop-down list to select a project it should belong to. This will make the task of adding fast tasks more easy.
