### ISSUE TITLE
Project > New Actions; Respect Show/Hide Options

### ISSUE THREAD

**Issue by roma0104** [roma0104/gsd5#42]
Currently new Actions created from the Project Lists do not respect the user's preference for the displaying or hiding of new Actions.  They should behave as 'pure' Actions created in the Collect tab.

**Comment by danielo515** [comment]
This ticket should be reopened. New actions are still being opened, no matter what you have selected. I want to create new tasks silently, not to end with a new tiddler on my river for each new action. Tested on Firefox mobile.

**Comment by danielo515** [comment]
Ok, my bad. I did not tried on the nightly. Works well.
