### ISSUE TITLE
The readme should include some advice for those who do want to build it from source

### ISSUE THREAD

**Issue by simonbaird** [roma0104/gsd5#43]
For someone who wants to contribute a patch, it would be useful to help them get started with a local build process rather than require them to figure it out for themselves.

What is the hack/build/test process you use while developing?

Ps, I'm prepared to guinea-pig/review the instructions, (or perhaps even write them if you can give me a pointer re the recommended way to do it).

**Comment by roma0104** [comment]
Certainly, Simon.  I do a short write up on how to build it.

**Comment by roma0104** [comment]
Added some build directions if you would like to try it and see if you can follow along.
50b5783b0fe4cec011a9c6e69b7ec912a1254833

**Comment by simonbaird** [comment]
I had some ideas about making it easier, see #44 .

**Comment by simonbaird** [comment]
Actually I think a Makefile would be better than using shell scripts, but @Jermolene doesn't like the idea much, (see https://github.com/Jermolene/TiddlyWiki5/issues/383 )

**Comment by Jermolene** [comment]
@simonbaird my concern is wanting people to be able to build TW5 without any dependencies beyond node (and npm). That might mean just being able to do a basic `tiddlywiki editions/tw5.com --build index` command. I'm not against using make for the tiddlywiki.com build process -- to be honest, I think it would really help.

**Comment by simonbaird** [comment]
@Jermolene Oh yeah I understand the reasoning. The context over here is I am tinkering with a couple of build related bash scripts and since have no way (or motivation) to test equivalent .cmd files, I was pondering a cross platform solution once again.

**Comment by simonbaird** [comment]
@Jermolene Btw, I used TIDDLYWIKI_PLUGIN_PATH quite effectively in e2436d5 and 51fb1aa over in #44 , very handy.. :)

**Comment by Jermolene** [comment]
@simonbaird would it make life easier if you could add to the edition/plugin paths via TW commands:

```
tiddlywiki editions/myedition --verbose \
  --addpluginpath myproject/plugins
  --build index
```

**Comment by simonbaird** [comment]
@Jermolene Yeah that would be nice, especially if it could find plugins in multiple different directories.

**Comment by Jermolene** [comment]
It would. `TIDDLYWIKI_PLUGIN_PATH` already supports a list of paths. `--addpluginpath` would dynamically add an entry to the in-memory list.

**Comment by roma0104** [comment]
I had thought about creating a more "friendly" means of building with an edition file but that would place the the `.git` directory for both TW5 and GSD5 in the same root.  And there doesn't seem to be a good way to manage the two together.  Any ideas?

**Comment by simonbaird** [comment]
Yeah I think I've solved most of the problems, see my pull request #44. There are four commits:

- move core directory to plugins/gsd5/core
- add an "edition" file and a bin/serve.sh that can start TW5 from ../TiddlyWiki5 using the gsd5 edition
- add a similar bin/build.sh that can create an html
- update the readme re the above
