### ISSUE TITLE
Sort next Actions

### ISSUE THREAD

**Issue by Theodin** [roma0104/gsd5#45]
In my GSD5 copy, I have ~10 next actions. Is there a way to order them by project, deadline or something else? Or am I using it wrong as I am fairly new to the whole GTD thing?

**Comment by roma0104** [comment]
Hello Theodin.  

GSD5 is based upon a project management technique and this implementation is a bit of compromise between practicality, the book, and opinions.  Ha.  

While GSD5 is meant to be somewhat malleable to fit to your own needs, there are a couple structures that give it some actual usefulness.  First there are Realms; Realms divide projects and actions into large categories where crossover is rare or impossible.  For example, I personally divide my actions and projects into Work, Personal, and Programming.  If you find you have too much going on in one Realm you might consider splitting the Realm (I write C++, and HTML/Javascript as a hobby, it could fit in my personal life but I made it into its own Realm: Programming).

From my *personal* interpretation/misinterpretation of the book, Actions are not supposed to have priority and/or deadlines, they all need to be done as promptly as possible.  Ideally, if you work efficiently, promptly and manage your project correctly you shouldn't need deadlines, you should come out ahead any reasonable deadlines.

But there are a couple exceptions: Actions that can only be done at certain time (e.g. call Ira before she leaves) or Actions that need to be revisited at a later time (e.g. check my car's blinker fluid).  The Getting-Things-Done(GTD) model uses ticklers as reminders/deadlines, I purposely dropped this from GSD5/core as TW5/GSD5 is not a calendar program, and there are better reminder methods for people to use (Outlook, Google Calendar).  Though I do plan for this to return as a plugin.

You can group/sort Actions by any TW5 field that is present on an Action Tiddler.  If you wish to sort by Project, go to the Control Panel > GSD5 > Core and check `Group Actions in Dashboard by Project`.  This will group all Actions, regardless of status, by Project in all Action lists.  The default sort is `title`.

If you want to do something more interesting it takes a little mucking about in the guts but it is much easier with the newest release.  You can use the `<<gsd5-list>>` macro.  [See documentation](http://gsd5.tiddlyspot.com/#GSD5%20List%20Macro).  I need to update the documentation but a crash course:  

If I wanted to group all complete Actions by the date I created them I could simply create a new tiddler, or edit the Dashboard directly, and insert the following text:

```
<<gsd5-list title:"Complete Actions By Date" gsd_type:"action" gsd_complete:"true" groupBy:"created">>
```

Hope this helps. Let me know if there is any other questions or need help creating a list.

**Comment by Theodin** [comment]
Thanks for your kind words and explanations (and for closing this one so I got around to answering you).
Thanks to your tips, my actions are now organised and thus you closed this one rightfully :)
I have some more questions but I will open new issues as they are thematically different.

**Comment by roma0104** [comment]
Certainly Theodin.
Your questions and input, even on usage are always welcomed.

On Mon, Mar 2, 2015 at 2:55 PM, Theodin <notifications@github.com> wrote:

> Thanks for your kind words and explanations (and for closing this one so I
> got around to answering you).
> Thanks to your tips, my actions are now organised and thus you closed this
> one rightfully :)
> I have some more questions but I will open new issues as they are
> thematically different.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roma0104/gsd5/issues/45#issuecomment-76820195>.
>



-- 
Roma Quintin Hicks
