### ISSUE TITLE
Future projects without next actions should not appear in 'No Next Action' list

### ISSUE THREAD

**Issue by simonbaird** [roma0104/gsd5#48]
I think for "Future" projects it's okay to not have a current next action, so they shouldn't be included in the list of projects displayed by plugins/gsd5/core/ui/no-next-action.tid.

**Comment by roma0104** [comment]
I agree Simon.  I have a commit queued up.

**Comment by simonbaird** [comment]
:+1:

**Comment by simonbaird** [comment]
Just noticed completed projects were also include. Should be fixed by PR #56.

**Comment by roma0104** [comment]
Thanks Simon... I must have had my eyes closed when I wrote that.
