### ISSUE TITLE
Clean Up Bluebox Toggle Button

### ISSUE THREAD

**Issue by roma0104** [roma0104/gsd5#52]
I forgot to finish the toggle button's extra code that presents the button in the "More Actions" list.
It might remain somewhat ugly due to the fact the button is actually a checkbox.

**Comment by Theodin** [comment]
Whats the BlueBox? Is it the realm-selector?
And whats the "more actions list"?
BTW I am using the stable version so maybe those features are beta-only?

**Comment by roma0104** [comment]
The BlueBox is a quasi-official nickname for the blue area that most of the GSD5 controls are contained.  It is dynamic and will show different controls depending on the tiddler that contains it.  It can contain the Realm Selector but is not the Realm Selector itself.  It is also designed to be modular allows other plugins to display their controls within the BlueBox.  The BlueBox has been present since initial release.

The More Action list is a part of TiddlyWiki5's stable UI.  It is the downwards facing arrow that when clicked shows addition actions that can be on the current tiddler.  Any of these extra actions can be displayed on the tiddler's toolbar by going to `Control Panel > Appearance > Toolbars` and selecting the desired button.  

The issue in this case is the odd looking button displayed in the More Actions list.  The "dial" icon (it looks a bit more like an eye).  It is offset and does not have any text explaining its use.  It was a bit of hack and probably shouldn't have gone out with the release.  While the rest of the buttons on the toolbar are Button Widgets, the needed for the toggling mechanic resulted in the GSD5 button actually being a dressed-up checkbox; HTML buttons nor the Button Widget actually support toggling.  It needs more CSS love to look better.  The Hide/Show BlueBox button is a new feature that came out with v0.5-beta.

**Comment by Theodin** [comment]
Ah. I stumbled over that term while reading the new beta release notes so thanks for your elaborate explanation.

**Comment by tobibeer** [comment]
Perhaps rather than calling it BlueBox, perhaps use a term like GSDPanel.

**Comment by roma0104** [comment]
Mmm.  I like that.  Much better descriptor for that.

**Comment by rob-bb** [comment]
Hi, Is it possible to have the BlueBox default to its collapsed state?  I have the toggle button and use it but it only lasts for the current session.

**Comment by netrc** [comment]
Agree. And, in general, need to have the GUI be more compact and default to hiding settings etc. In fact, when "collapsed", I'd move it to the top nav line, i.e. not have the blue box icon take up any vertical space in the info pane at all.

**Comment by roma0104** [comment]
@rob-bb Sure I think that is a reasonable interface request.  

@netrc My initial concern with completely hiding the any indication of the collapsed Blue-Box/GSDPanel is that it could be ambiguous to its presence or state, especially to new users.  Could be a UI plugin or perhaps make the collapse button default to *on* with/or have another way to indicate collapsed state?  E.g. A blue line at the top of the tiddler, colourise the button, etc.

**Comment by netrc** [comment]
Sorry - agree it shouldn't be "hidden" but moved to be inline with other items. In general, I'd like the tiddler content to be as compact as possible; a blue-box icon on a line all its own takes up valuable vertical space.
