### ISSUE TITLE
Projects and actions in different Realms?

### ISSUE THREAD

**Issue by Theodin** [roma0104/gsd5#53]
I noticed that actions only appear in the Dashboard if the realm they are in coresponds to the realm of the project they are part of.
Example:
The project is " My friends birthday" (realm="at home") which has an action called "buy a gift" (realm="shopping").

Am I using realms the wrong way or am I asking for something not implemented yet?

Thanks for your project!

**Comment by roma0104** [comment]
A couple contributors and I discussed this a while back.  
https://github.com/roma0104/gsd5/issues/20
One of the users organises his GSD5 in a way similar to yours, not necessarily wrong, just not the attempted loose structure GSD5 imposes.

Essentially you are bending Realms into something it was not prescribed to do initially.  Realms are meant to separate actions that shouldn't ever meet, ideally.  I, for example separate my personal GSD5 in Work/Personal/Programming.  You can hack Projects to act cross-Realm by using no Realm at all, though some of the drop lists for parenting tiddlers may not display correctly.  Generally you want all your Actions and Projects to have a Realm.

In my opinion, a better candidate for you needs is Contexts.  Contexts can span Projects and Realms.  Contexts also generate a handy list of all Actions that have been assigned to it, creating your shopping list dynamically.

You can create a Context that is specific to a Realm or you create a Context that belongs to the "all/none" Realm which then shows up in all Realms.  Once the Realm has been created go to your Action, click the Context Frame in the BlueBox.  Checkmark the Context to assign it.  An ordinary TW5 tag should appear on the Action tiddler (usually a pill shaped, yellow symbol with the name of the context).  

You can see your shopping list by clicking the yellow tag which displays a droplist.  Select the entry with the name of the tag.  This navigates to a tiddler with the same name as your context that conveniently displays all you actions with your "shopping" tag.

**Comment by Theodin** [comment]
As they say in Launchpad:
Thanks, that solved my question. :)
I will upgrade to the beta in the next days and try out the Contexts.
