### ISSUE TITLE
Status should be a simple drop down

### ISSUE THREAD

**Issue by danielo515** [roma0104/gsd5#64]
Or something similar. 

Is really useless to have three buttons just to show to which state you can switch to. This is specially annoying on mobile, where the space is limited. From my point of view a simple drop down it's enough. Maybe you can style the drop down to look like current buttons. 

Regards

**Comment by tobibeer** [comment]
For usability's sake the buttons are a win => one simple click, not one to open a dropdown and then a fiddly second, even changing the mobile ui! => distracting

What could be considered is having the disabled options only show up on-hover. This, however, would also be a real problem for mobile.

Maybe the lack of responses so far is also an indication that there has yet to be someone to agree.

**Comment by roma0104** [comment]
I am closing this.  Currently the status buttons consume one line and no more, a drop list doesn't consume any less (on my screen, anyhow).  

No further users seemed to be interested in this as well.
