### ISSUE TITLE
Realm selector is too large

### ISSUE THREAD

**Issue by danielo515** [roma0104/gsd5#66]
I'm talking about the dashboard. There is no need to show all the realms at once. It eats up vital space, specially ok mobile. It will be enough a simple drop down selector, or make it collapsible (like the context selector)

**Comment by danielo515** [comment]
Hello.
Thank you for the compact realm selector. I also love the config option `collapse widgets when possible`. I think that option should include the blue-box controls. It's a bit disappointing to hit a checkbox that claims to collapse all widgets and only affects one.

Regards.

**Comment by roma0104** [comment]
Some widgets are only 'one line' deep, I don't see how compressing them into a expanding box would improve.  I provided that for any future widgets that might need to be minimized, and any subsequent widgets we might think needs some kind of minimize feature.
