### ISSUE TITLE
Changing tags without going into edit mode

### ISSUE THREAD

**Issue by dominikalexander** [roma0104/gsd5#73]
It would be great if tags could be added, changed and deleted without going in edit mode. Furthermore I would like to see that there was a possibility to rename, remove or add tags to tiddlers with a certain criteria eg change all tiddlers with the tag computer to @computer or ad all tiddlers with contact Steven the tag @bangkok.

**Comment by roma0104** [comment]
This might be an issue that needs to be addressed to the developers at https://github.com/Jermolene/TiddlyWiki5.  Changing tags, unless tied to HTML elements like `<$checkbox>`, require you to change the tiddler to edit mode.

**Comment by dominikalexander** [comment]
Thank you Roman for the clarification.
